# action.yml
name: 'Fabric Ansible Action'
description: 'Fabric Ansible Action'
inputs:
  playbook:  # id of input
    description: 'playbook to run'
    required: true
    default: 'playbook.yaml'
  argsfile:  # id of input
    description: 'additional args file'
    required: false
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.playbook }}
    - ${{ inputs.argsfile }}