#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Create components for an ordering organization
  hosts: localhost
  vars:
    state: present
    organization_name: "{{ ordering_org_name }}"
    organization_msp_id: "{{ ordering_service_msp }}"
    wallet: "{{ROOT}}/_cfg"
  vars_files:
    - "{{ROOT}}/_cfg/auth-vars.yml"
    - "{{ROOT}}/_cfg/fabric-common-vars.yml"
    - "{{ROOT}}/_cfg/fabric-ordering-org-vars.yml"
  roles:
    - ibm.blockchain_platform.ordering_organization
