---
- hosts: localhost
  vars_files: 
    - "{{ROOT}}/_cfg/operator-console-vars.yml"
  tasks:
    - ansible.builtin.debug:
        msg: "Hello {{namespace}}"
    - name: Get a list of all pods from any namespace
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: fabricinfra
      register: pod_list
    - ansible.builtin.debug:
        msg: "{{pod_list}}"

    