# Copyright the Hyperledger Fabric contributors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: 001-general

on:
  pull_request:   
  workflow_dispatch:

env:
  GITHUB_SHA: ${{ github.sha }}


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup and create the KIND cluster
        run: |
          ./scripts/kind_with_nginx.sh

          mkdir -p _cfg
          kubectl config view --raw > _cfg/k8s_context.yaml
    