# Copyright the Hyperledger Fabric contributors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: crds-operator

on:
  create:
    tags:
      - "*"      
  workflow_dispatch:

env:
  GITHUB_SHA: ${{ github.sha }}
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_CLOUD_REGION: eu-gb
  REGISTRY_HOSTNAME: uk.icr.io
  CLUSTER_ID: ${{ secrets.CLUSTER_ID }}  
  PROJECT_NAME: samara-alpha
  

jobs:
  authenticate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ibm-blockchain/ofs-ansibe:sha-ac6fd82
      volumes:
        - cloud-base/infrastructure/operator_console_playbooks:/playbooks
        - _cfg:/_cfg
    steps:
      - uses: actions/checkout@v3
      # Download and Install IBM Cloud CLI
      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version
          ibmcloud config --check-version=false
          ibmcloud plugin install -f kubernetes-service
          ibmcloud plugin install -f container-registry      
    # Authenticate with IBM Cloud CLI
      - name: Authenticate with IBM Cloud CLI
        run: |
          ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}" -g Blockchain-Test
          ibmcloud cr region-set "${IBM_CLOUD_REGION}"
          ibmcloud cr login

          mkdir -p _cfg
          ibmcloud ks cluster config --cluster ${CLUSTER_ID}  --output yaml > _cfg/k8s_context.yaml

      - name: BuildData
        id: builddata
        run: |
          ls -lart
          ansible-playbook -e KUBECONFIG=/_cfg/k8s_context.yaml /playbooks/01-operator-install.yml

          
          
